# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
rvm: 2.3.0
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods -v '1.0.1' --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example
install:
script:
- set -o pipefail && xcodebuild test -workspace Example/IGXMLReader.xcworkspace -scheme IGXMLReader-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
